dist: trusty
sudo: false
language: ruby
script: "./script/cibuild"

addons:
  postgresql: '9.6'
  firefox: latest

before_install:
- gem update --system 2.7.4
- gem --version
- mkdir geckodriver
- wget https://github.com/mozilla/geckodriver/releases/download/v$GECKODRIVER_VERSION/geckodriver-v$GECKODRIVER_VERSION-linux64.tar.gz
- tar -xzf geckodriver-v$GECKODRIVER_VERSION-linux64.tar.gz -C geckodriver
- export PATH=$PATH:$PWD/geckodriver

notifications:
  slack:
    secure: lPI2LWfiFjs1hLF/dPkmplZ6c56Kdri95wI21QzW73ctM9+Dyn01hGg0gYMBoW8mRsk3Je1yeJpemyGNFt7Ul2vpbZTSKIvMMh715JL9Y6QtQEkX/Tspv+lGlw9PcqxVRaCVDDTRwwr05N+h2AjBnWVYurlIbWJ+ihUB+iHXVufECp+hAn6CIDjGdXA5hMWQImCK4vZllMcYsvuInWCYz0JZchdDyUlJKKlmCfYTznC9VTVJLkxhTO7maCTtlNif1tPcUXI2dFyQ/1xZUbkYNC4etUAbf3zSG6CFaVY/FFIIC7h/g537kIwvoKqrkSRtV3IaH6FqW6qbdkx2oLSiwieXIo1cjkjfBDlynZ0/GAAHr+GV+3Mm9acxFqC7fxWcSc5XzdZxm7i3AWFrcx4KdgAxXFlDWp+pQuBOo+3Ge+3KG5Iz8+RdXM7xhFQuyDKslDXZ+0fWV1f7EfxNxQKD9LCnr8+9seoLLaNymfozRWUSKcFiXL13wEgV0FuMCy0Ci2DkNThlUJESQX3hZiqCt1R1SPFzHQPzciXeN1JlpYaAOklvAyP0TNzIrDmzzlsmKdsa4B3Lfq9tUx0QceqovLSJCbOs92W2WD2Gre9kVEpav6eLSM6hSSF4iYdxXuwLUBNYy8El1jSqZ/Gb0sb5Km0J7EZfw2vt8Nu56demgLE=

env:
  global:
    - GECKODRIVER_VERSION="0.19.1"
    - MOZ_HEADLESS=1
    - CODECLIMATE_REPO_TOKEN: 70b1a0a5ca106d965eb0570c0e4b7577d76c352305fb5719aa984eeae4941bdf

