default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  host: localhost
  database: crimethinc_development

test:
  <<: *default
  host: localhost
  database: travisci_test

production:
  <<: *default
  database: crimethinc_production
  username: crimethinc
  password: <%= ENV['CRIMETHINC_DATABASE_PASSWORD'] %>
